name: PR Risk Checker
description: Check if a pull request is risky based on code complexity and changes

inputs:
  repo_owner:
    required: true
    description: Owner of the GitHub repository
  repo_name:
    required: true
    description: Name of the GitHub repository
  pr_number:
    required: true
    description: Pull request number
  token:
    required: true
    description: GitHub token to call GitHub API

outputs:
  is_risky:
    description: "Whether the PR is considered risky"
    value: ${{ steps.run_risk.outputs.is_risky }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r "$GITHUB_WORKSPACE/Code_Review_Analytics/requirements.txt"
      shell: bash

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE/Code_Review_Analytics" >> $GITHUB_ENV
      shell: bash

    - name: Run PR Risk Checker
      id: run_risk
      run: |
        echo " Running PR Risk Checker with:"
        echo "  repo_owner=${{ inputs.repo_owner }}"
        echo "  repo_name=${{ inputs.repo_name }}"
        echo "  pr_number=${{ inputs.pr_number }}"

        export GITHUB_TOKEN="${{ inputs.token }}"

        python -m pr_risk_checker.cli \
          --repo_owner="${{ inputs.repo_owner }}" \
          --repo_name="${{ inputs.repo_name }}" \
          --pr_number="${{ inputs.pr_number }}" \
          --token="${{ inputs.token }}" > output.txt || true
        tail -n 10 output.txt

        IS_RISKY=$(grep -oP 'is_risky=\K(true|false)' output.txt | tail -1)
        echo "Detected is_risky=$IS_RISKY"
        echo "is_risky=$IS_RISKY" >> "$GITHUB_OUTPUT"
      shell: bash
