name: Risk Check on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-risk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (analytics-user)
        uses: actions/checkout@v3

      - name: Checkout Code_Review_Analytics repo
        uses: actions/checkout@v3
        with:
          repository: prerana2005/Code_Review_Analytics
          path: Code_Review_Analytics
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          pip install -r Code_Review_Analytics/requirements.txt

      - name: Run Risk Checker
        id: riskcheck
        uses: ./.github/actions/risk-checker
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Assign reviewer if risky
        if: steps.riskcheck.outputs.is_risky == 'true'
        run: |
          python pr_risk_checker/assign_reviewer.py
        working-directory: Code_Review_Analytics
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REVIEWERS: "senior-reviewer"
