name: Risk Check on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  analyze-risk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (analytics-user)
        uses: actions/checkout@v3

      - name: Checkout Code_Review_Analytics repo
        uses: actions/checkout@v3
        with:
          repository: prerana2005/Code_Review_Analytics
          path: Code_Review_Analytics
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requirements
        run: |
          pip install -r Code_Review_Analytics/requirements.txt

      - name: Run Risk Checker
        uses: ./Code_Review_Analytics/.github/actions/risk-checker
        with:
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Assign senior reviewer if risky
        if: steps.run_risk.outputs.is_risky == 'true'
        run: |
          echo "Assigning senior reviewer to risky PR..."
          gh pr edit ${{ github.event.pull_request.number }} \
            --repo "${{ github.repository }}" \
            --add-reviewer senior-dev-username
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
